language: node_js

node_js: 14

addons:
 apt:
  packages:
  - lftp
 ssh_known_hosts:
 - w00976cb.kasserver.com

install:
- npm install --global grunt-cli
- npm install

script:
- grunt

after_success:
- grunt deploy

notifications:
 email:
 - team@redaxscript.com
