name: ci

on: [ push, pull_request, workflow_dispatch ]

jobs:
 sync:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Node 15
    uses: actions/setup-node@v1
    with:
     node-version: 15
  - run: sudo apt install lftp
  - run: npm install
  - run: grunt build
  - run: grunt optimize
  - run: grunt deploy
    env:
     FTP_URL: ${{ secrets.FTP_URL }}
